# 활성화 된 설정 파일을 로그에서 확인 할 수 있도록

server:
  port: 8080

logging:
  level:
    com.slack.slack: DEBUG

spring:
  # DB 설정 => 실제 운영시 이 부분을 변경해주세요.
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  mail:
    host: smtp.gmail.com
    protocol: smtp
    port: 587
    username: ''
    password: ''
    properties.mail.smtp:
      nickname: ''
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  messages:
    basename: messages
    encoding: UTF-8

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # metrics 설정
  endpoint:
    metrics:
      enabled: true
    # metrics & prometheus 설정
    prometheus:
      enabled: true
  # prometheus 설정
  metrics:
    export:
      prometheus:
        enabled: true


custom:
  mailtemplate: 'templates/mailTemplates/'
  tempfile: 'C://dev//temp'

system:
  secretkey: webcompiler

